### ISSUE TITLE
More readable template errors

### ISSUE THREAD

**Issue by vba** [tomcz/spring-stringtemplate#2]
Hi,

Do you know if we could make StringTemplate "compilation" errors more readable (make it appear in views instead of terminal) and comprehensible (reduce stack trace size, indicate line etc) and make this feature configurable ? Currently all that we have is one mile stack trace that usually says about an error but you have to find it yourself.

**Comment by tomcz** [comment]
StringTemplate provides a org.antlr.stringtemplate.StringTemplateErrorListener interface to log template errors. The default from StringTemplate simply logs the stack trace to System.err. I've made the listener a configuration option for the StringTemplateViewResolver and have provided a sample Slf4jStringTemplateErrorListener implementation to at least give me logging that goes into the same log file as the rest of my application's logging.
