### ISSUE TITLE
I18n in StringTemplate spirit v1.2

### ISSUE THREAD

**Issue by vba** [tomcz/spring-stringtemplate#3]
Hi, 

Nice features. I think that we can made i18n more in ST spirit, this approach offer us a little bit more readability? (and maybe performances?). Currently we must do some think like that : 

$messages.("message.with.arguments").(arg1).("? & ?").(arg2).to_s$
//message.with.arguments = {0} --> {1} --> {2}

Approach that I propose permit to do this:

$arg1, "? & ?", arg2  : {s0, s1, s2 | $messages.("message.with.arguments")$}$
//message.with.arguments = {0} --> {1} --> {2}

If you are interested I could send you my realization. Otherwise we've produced helpers for spring security, escaping, regex matcher. And I hope that I could get a bit of time to see how we could improve errors displaying (short stack trace and error line indication like in play! templates).

**Comment by tomcz** [comment]
Interesting idea. I prefer 

$messages.(["message.with.arguments", arg1, "? & ?", arg2])$

to get the same effect. This has now been committed and will be released as version 1.3 in the future.

HTML, URL, JS and XML escaping is done by the WebFormat and WebAttributeRenderer classes so you don't need to create your own. HTML escaping is on by default as the WebAttributeRenderer is the default renderer for any object that does not have its own custom renderer registered with the StringTemplateViewResolver.
