### ISSUE TITLE
SpringTemplate is 4.x now,please upgrade.

### ISSUE THREAD

**Issue by kevinz** [tomcz/spring-stringtemplate#5]
Can't support SpringTemplate4 cause it's totally rewrote,the api is changed,but it's not difficult to do the migration,please support SpringTemplate4,thanks.

**Comment by tomcz** [comment]
Actually the migration is quite difficult so please be patient while I figure out how to best use the new version.

**Comment by kevinz** [comment]
I'd really appreciate your work.

btw:How do you think the way ST integrate with security&authentication framework?Such as shiro,
"hasPermitions","hasRoles" are very common operations for authentication on template or jsp.I know it's forbidden in ST,but i can't figure out a solution about this,should i export all permitions and roles as bool value to the model .

**Comment by tomcz** [comment]
You can create a map of permissions & roles, put it into your model and then access it that way.
On the other hand you can extend com.watchitlater.spring.CachingDataMap and perform the role evaluation in a lazy manner - along the same lines as com.watchitlater.spring.MessagesMap.

**Comment by kevinz** [comment]
Got it,like MessagesMap,it lookes like $permissions.(["has","add","delete"]).Thanks.

**Comment by kevinz** [comment]
I got another question,help please.I'm not that familiar with ST,but i think it's a ST limitation.
In this case,$bindStatus.("command.name") will get the BindStatus object via "command.name" from context,but what if both "command" and "name" are variable,command and name are all string.I've tried:
$bindStatus.($command.name$)$,
$bindStatus.(command.name)$ , (it wiil treat name as command's property,which is empty)
$bindStatus.($command$.$name$)$
...
ST does not support concat two string variable as a new string variable,like  $$command$.$name$$,i think it's the reason.I just want to make the template have more chance to reuse,what's recommendation?
